version: "3.8"

services:
  app:
    container_name: xyz-multifinance-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: always